spring:
  application:
      name: springbatch-test
  datasource:
    url: jdbc:mariadb://localhost:43306/batch_example_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  batch:
    job:
      name: ${job.name}
#    jdbc:
#      initialize-schema: always
